{% set name = "pyct" %}
{% set version = "0.6.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d4e513b2cf35b6165605ae5fce5f2a49985bc67473c579de85134b8c71d374a8

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv
  entry_points:
    - pyct=pyct.__main__:main

requirements:
  host:
    - python
    - pip
    - hatchling >=1.25.0
    - hatch-vcs >=0.4.0
  run:
    - python
    - param >=1.7.0
    # extras_require for 'cmd':
    - pyyaml
    - requests

test:
  source_files:
    - pyct/tests
  imports:
    - pyct
    - pyct.build
    - pyct.cmd
    - pyct.report
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pyct --help
    - pytest -v pyct/tests

about:
  home: https://github.com/holoviz-dev/pyct
  summary: Python packaging Common Tasks
  description: |
    A utility package that includes:
    1. pyct.cmd: Makes various commands available to other packages. (Currently no sophisticated plugin system, just a try import/except in the other packages.)
    The same commands are available from within python. Can either add new subcommands to an existing argparse based command if the module has an existing command,
    or create the entire command if the module has no existing command. Currently, there are commands for copying examples and fetching data. See
    2. pyct.build: Provides various commands to help package building, primarily as a convenience for project maintainers.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  dev_url: https://github.com/holoviz-dev/pyct
  doc_url: https://github.com/holoviz-dev/pyct

extra:
  recipe-maintainers:
    - ceball
