{% set name = "pyct" %}
{% set version = "0.4.8" %}
{% set sha256 = "23d7525b5a1567535c093aea4b9c33809415aa5f018dd77f6eb738b1226df6f7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - param >=1.7.0
    - python
    - pip
  run:
    - param >=1.7.0
    - python
    - pyyaml
    - requests

test:
  imports:
    - pyct
    - pyct.cmd

about:
  home: http://github.com/pyviz/pyct
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: python package common tasks for users (e.g. copy examples, fetch data, ...)

extra:
  recipe-maintainers:
    - ceball
