{% set name = "pyct" %}
{% set version = "0.4.6" %}
{% set sha256 = "df7b2d29f874cabdbc22e4f8cba2ceb895c48aa33da4e0fe679e89873e0a4c6e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - param >=1.7.0
    - python
    - pip
  run:
    - param >=1.7.0
    - python
    - pyyaml
    - requests

test:
  imports:
    - pyct
    - pyct.cmd

about:
  home: http://github.com/pyviz/pyct
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: python package common tasks for users (e.g. copy examples, fetch data, ...)

extra:
  recipe-maintainers:
    - ceball
