travis:
  secure:
    BINSTAR_TOKEN: YyCqYCnTadvRMxMFZIiN1DpwIg96No9D+VIeJHDA4JxofKS8GKQSscJhlmwxz2taA9p60bXUh/AOAOp1/RoIySlQ0ZL8rXWMk0K8uYhrqxl34SVkqFlVMGEfoyhfv9NbGQy3YAB+5Y7AFxlfijgtBBckD4b5sf8Q/07c1ThEzn33KlER9yTtLOVsv4It73qOe9UjL2IR86GGJmjrARrj9VQtjO2ciBpYvp4jc9ov8uWcNNIkiEVJTwzcyVHnyEZeKSGmV1NuHSXjVM6L9DgSupYxOwUkipH1XDsaP7/PbtqCeuUel2sOCFoV4iO/RhElr8oGRpuyVfAkNIUkrdfcIuCQTNjV0t9Guq2mY1r+KeMxBkgHV3e1vRP6W17/JvuW1W2p5EBSHnzfRdaD8YQLhbBhfbflqahgvtH5gBNTo9VOuL9+WFlO8XPcJA8PemzPc8k8AZvP1wSGAMR83+Vg7IFtQ7ySMbR2ngxGf69RYaWJyDtpUzgq8agkZqNz3GiMYX5Ns69Y6hELZ1hHtL8Hq5Jcx/I9iWJu73E7PJ2a+bJy/lGByw3+khJNz2TVNSI4aSsmRw2kmHz+zpTHe4Q0+X3u5ZHVU6pAWDxbAC7Ea4TMurds3kScc6dMMg2hV+wQmNl7YhqiQcvrgHEPcsAeACC1U7yvqsJ4xpveVIrF+kM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
